"""Prove the Python encoder (board.py) and the in-browser JS encoder
(ai-lab/app/components/ChessDemo.js) produce byte-identical tensors.

If they ever drift, the deployed ONNX model gets garbage input and plays terribly,
silently. So this is a hard gate before any retrain/deploy of a new encoding.

  python parity_check.py           # writes parity_fens.json (FENs + reference tensors)
  node parity_check.mjs            # checks the JS encoder against it

Positions are generated by random legal play so the extra planes (castling loss,
en-passant, fifty-move clock) actually get exercised.
"""
import json
import random

import chess

from board import board_to_tensor, N_PLANES


def collect(n_positions=1000, seed=0):
    random.seed(seed)
    seen = []
    ep_count = 0
    while len(seen) < n_positions:
        board = chess.Board()
        # random game up to a random length
        for _ in range(random.randint(0, 60)):
            if board.is_game_over():
                break
            seen.append(board.fen())
            if board.ep_square is not None:
                ep_count += 1
            board.push(random.choice(list(board.legal_moves)))
            if len(seen) >= n_positions:
                break
    print(f"collected {len(seen)} positions ({ep_count} with an en-passant square)")
    return seen


def main():
    fens = collect()
    out = []
    for fen in fens:
        t = board_to_tensor(chess.Board(fen))
        assert t.shape == (N_PLANES, 8, 8), t.shape
        out.append({"fen": fen, "t": t.reshape(-1).astype(float).tolist()})
    with open("parity_fens.json", "w") as f:
        json.dump({"n_planes": N_PLANES, "cases": out}, f)
    print(f"wrote parity_fens.json ({len(out)} cases, {N_PLANES} planes) — now run: node parity_check.mjs")


if __name__ == "__main__":
    main()
